<?php
/**
 * Created by PhpStorm.
 * User: eivindbakke
 * Date: 2/27/15
 * Time: 7:13 PM
 */

class Event {

    public $id; //to be autogenerated by us later

    public $title;
    public $details;
    public $start;
    public $end;
    public $creator;

    public function __construct($title, $start, $end, $creator, $details = NULL) {
        $this->title = $title;
        $this->start = $start;
        $this->end = $end;
        $this->creator = $creator;
        $this->details = $details;
    }

}